# Generated by rust2rpm 27
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate stylua

Name:           rust-stylua
Version:        2.3.1
Release:        %autorelease
Summary:        Code formatter for Lua

License:        MPL-2.0
URL:            https://crates.io/crates/stylua
Source:         %{crates_source}
Source:         stylua-2.3.1-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          stylua-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A code formatter for Lua.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc README.md
%{_bindir}/stylua

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build -a
%{cargo_license_summary -a}
%{cargo_license -a} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install -a
# FIXME: install shared library

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
%autochangelog
